# 提前定义好公司信息，以及公司所在的城市，区
menu_list  = {
    '上海':{
        '浦东新区':{
            '蚂蚁金服':['jack','tom','marry'],
            '2345.com':['Adrian','Ahern','Andrew'],
            '华语兄弟':['Baird','Barlow','Bartholomew'],
            '浦发银行':['Carey','Cash','Cedric'],
            },
        '虹口区':{
            '星联科技':['Dennis','Dominic','Douglas'],
            '新果科技':['Earl','Edmund','Elliot'],
            '上海童石':['Fabian','Ford','Franklin'],
            '墨狸游戏':['Gavin','George','Glenn'],
            },
        '崇明岛':{
            '上海联通':['Hale','Hamiltion','Harold'],
            '美团点评':['Ingemar','Ivan','Ives'],
            '嘉丰瑞德':['Jesse','Julian','Kelly'],
            '上海移动':['Kevin','Lance','King'],
            },
    },
    '北京':{
        '西城区':{
            '赞同科技':['Lawrence','Les','Lewis'],
            '百视通':['Marcus','Matt','Meredith'],
            '小牛计划':['Ogden','Oliver','Oscar'],
            '极玩客':['Page','Patrick','Pete'],
            },
        '东城区':{
            '顺丰优选':['Quennel','Ralap','Reginald'],
            '海睿网络':['Samuel','Simon','Stanford'],
            '平安保险':['Theobald','tom','Timothy'],
            'GOLA科技':['Ulysses','Valentine','Vincent'],
            },
        '海淀区':{
            '普汇金服':['Walker','Webb','Webster'],
            '小米':['Yale','Yehudi','Zebulon'],
            '用友':['Woodrow','Steward','Ron'],
            '伙伴网':['Patrick','Nathan','Moore'],
            },
    },
}
